# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - myCard

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://github.com/isha17s/card/blob/main/index.html/
        username: ${{ secrets.AzureAppService_ContainerUsername_b666a37a86a2473e9db20ea6ed2a8288 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0a2c0a5de81e4b208fafa28a9be1c616 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: github.com/isha17s/card/blob/main/index.html/${{ secrets.AzureAppService_ContainerUsername_b666a37a86a2473e9db20ea6ed2a8288 }}/isha17s/card/blob/main/index.html/isha17s/card/card/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myCard'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c323d90170b54ace96aa0809ea17028b }}
        images: 'github.com/isha17s/card/blob/main/index.html/${{ secrets.AzureAppService_ContainerUsername_b666a37a86a2473e9db20ea6ed2a8288 }}/isha17s/card/blob/main/index.html/isha17s/card/card/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'